In [1]:
import numpy as np

In [2]:
a = np.arange(10)
b = np.arange(20)

In [3]:
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
x=np.arange(20).reshape(5,4)

In [7]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [8]:
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(type(a))

1
(10,)
10
int32
4
<class 'numpy.ndarray'>


In [9]:
print(b)
print(b.dtype)
print(type(b))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
int32
<class 'numpy.ndarray'>


In [18]:
d = np.linspace(1, 2,10, endpoint=True)
print(d)

[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [21]:
d = np.linspace(1, 2, 10, endpoint=True)
print(d)


[1.         1.11111111 1.22222222 1.33333333 1.44444444 1.55555556
 1.66666667 1.77777778 1.88888889 2.        ]


In [23]:
(3,2)

NameError: name 'reshape' is not defined

In [24]:
f = np.fromfunction(lambda i, j: i == j, (5,5), dtype=int)
f

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [41]:
a = np.arange(10).reshape(3,4)
print(a)

ValueError: cannot reshape array of size 10 into shape (3,4)

In [30]:
a/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [31]:
a*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [32]:
a-2

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [33]:
a/2

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [34]:
b = a.transpose()
b

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [35]:
print(a.sum())

66


In [42]:
print(a.min(), a.max())

0 11


In [46]:
b = a*np.e/12
print(b)

[[0.         0.22652349 0.45304697 0.67957046]
 [0.90609394 1.13261743 1.35914091 1.5856644 ]
 [1.81218789 2.03871137 2.26523486 2.49175834]]


In [47]:
b = a*np.pi/12.0
print(b)

[[0.         0.26179939 0.52359878 0.78539816]
 [1.04719755 1.30899694 1.57079633 1.83259571]
 [2.0943951  2.35619449 2.61799388 2.87979327]]


In [49]:
d = b + a

In [50]:
d

array([[ 0.        ,  1.26179939,  2.52359878,  3.78539816],
       [ 5.04719755,  6.30899694,  7.57079633,  8.83259571],
       [10.0943951 , 11.35619449, 12.61799388, 13.87979327]])

In [51]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [53]:
a[2]

2

In [54]:
a[3:5]

array([3, 4])

In [61]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
a[3,2]

11

In [66]:
a[1:0,1:0]

array([], shape=(0, 0), dtype=int32)

In [67]:
a = a.flatten()
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [69]:
for r in a:
    print(r)
a = np.arange(12).reshape(4,3)
print(a)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [70]:
a = np.arange(10)
print(a)


[0 1 2 3 4 5 6 7 8 9]


In [71]:
x is a

False

In [72]:
x=a

In [73]:
x is a

True

In [77]:
x.shape = (5,2)
print(x)
a.shape

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


(5, 2)

In [78]:
a = np.arange(12)
c = a[:]
a.shape = (3,4)

print(a)
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [79]:
c[1] =-1
print(a)
print(c)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0 -1  2  3  4  5  6  7  8  9 10 11]


In [82]:
d = c[4:8]
print(d)

[4 5 6 7]


In [83]:
d

array([4, 5, 6, 7])

In [84]:
print(x is a)
print(x.base is a)
print(x.flags.owndata)
print(a.flags.owndata)

False
False
True
True


In [85]:
#Deep copy
d = a.copy()
d[:,:] = 0.0

print(a)
print(d)

[[ 0 -1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [86]:
#BOOLEAN INDEXING

In [87]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [88]:
a[a>6]=0

In [89]:
a

array([[0, 1, 2, 3],
       [4, 5, 6, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [92]:
a[a==0]= '1'

In [93]:
a

array([[1, 1, 2, 3],
       [4, 5, 6, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [96]:
a = np.arange(16).reshape(4,4)
a[np.logical_and(a > 4, a <= 12)] = 0
a

array([[ 0,  1,  2,  3],
       [ 4,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0, 13, 14, 15]])

In [97]:
a>8

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True]])

In [105]:
M = 0
N = 32
xmin = ymin = 0
xmax = ymax = 1

x = np.linspace(xmin, xmax, M, endpoint=False)
y = np.linspace(ymin, ymax, N, endpoint=False)

print(x.shape)
print(y.shape)
y

(0,)
(32,)


array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    , 0.53125, 0.5625 , 0.59375, 0.625  ,
       0.65625, 0.6875 , 0.71875, 0.75   , 0.78125, 0.8125 , 0.84375,
       0.875  , 0.90625, 0.9375 , 0.96875])

In [106]:
import time
import numpy as np
M = 0
N = 32

x = np.linspace(0.0, 1.0, M, endpoint=False)
y = np.linspace(0.0, 1.0, N, endpoint=False)


In [108]:
t0 = time.time()

g = np.zeros((M, N))

for i in range(M):
    for j in range(N):
        g[i,j] = np.sin(2.0*np.pi*x[i]*y[j])
        
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0 s


In [113]:
t0 = time.time()
g2 = np.sin(2.0*np.pi*x2d*y2d)
t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.0 s


In [114]:
#Concatenation

In [131]:
x = np.array([1, 2, 3, 4])
y = np.array([5,6,7,8,9,10])
m=np.concatenate([x,y])
m

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
a=np.array([11,12,13])
np.concatenate([x,y,a])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [120]:
grid = np.array([[10, 20, 30],
                 [40, 50, 60]])


In [126]:
grid2 = np.array([[70, 80, 90],
                [100,110,120]])

In [127]:
np.concatenate([grid, grid2])

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [132]:
m1,m2,m3,m4=np.split(m,[2,5,8])

In [133]:
m1

array([1, 2])

In [134]:
m2

array([3, 4, 5])

In [135]:
m3

array([6, 7, 8])

In [136]:
m4

array([ 9, 10])

In [138]:
x = np.arange(1, 6)
print(x)
np.add.reduce(x)

[1 2 3 4 5]


15

In [139]:
np.multiply.reduce(x)

120

In [140]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [141]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)